name: Sync with JIRA

on:
  # Allow manual triggering of the JIRA Sync
  workflow_dispatch: 
  # Automatically trigger whenever an issue is created/edited etc.
  issues: 
    types:
      - opened
      - edited
      - transferred
      - reopened

jobs:
  sync-to-jira:
    permissions: 
      contents: read
      issues: write
    uses: telicent-oss/shared-workflows/.github/workflows/jira-sync.yml@main
    with:
      jira-url: https://telicent.atlassian.net
      jira-project: CORE
      issue-mapping-file: .github/jira-mapping-rules.yml
      extra-sync-options: "--skip-existing --include-comments --extra-labels stream/smart-caches --jira-repository-field customfield_10036 --close-after-sync"
    # NB - As we're using a shared workflow in another organisation we can't use
    #      secrets: inherit here and MUST pass the secrets explicitly.  GitHub 
    #      Actions takes care of ensuring these are securely passed between this
    #      and the called workflow
    secrets:
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
      JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}

  
